- name: mongodb configure
  hosts: mongodb
  become: yes
  tasks:
    - name: copy mongodb repo
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo
        
    - name: instance mogodb 
      ansible.builtin.dnf:
        name: mongodb-org
        state: present

    - name: allow remote connection
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Start & Enable MongoDB Service
      ansible.builtin.Service:
        name: mongod
        enabled: yes 
        state: started
        

  